name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '💥 Breaking'
    label: 'breaking'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'
      - 'dependencies'
  default: patch
exclude-labels:
  - 'skip-changelog'
