name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: ./tools/composer validate

    - name: Install dependencies
      run: ./tools/composer install --no-interaction --no-progress

    - name: Run test suite
      run: ./tools/phpunit --bootstrap vendor/autoload.php tests
